apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
  labels:
    app: telegram-bot
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
        - name: telegram-bot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{- range .Values.env }}
            - name: {{ .name }}
{{- if .value }}
              value: "{{ .value }}"
{{- else if .valueFrom }}
              valueFrom:
{{ toYaml .valueFrom | indent 14 }}
{{- end }}
{{- end }}
          ports:
            - containerPort: 8080
