replicaCount: 1

image:
  registry: "ghcr.io"
  repository: "samtishka/telegram-bot"
  tag: "v1.0.0-3d600d6-linux-amd64"
  os: "linux"
  arch: "amd64"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

secret:
  teleToken: ""

TELE_TOKEN: ""

resources: {}
